### PR TITLE
Fixed Installation issues

### PR DESCRIPTION
**Pull request by SamSike**
Installation Guides for Windows (using WSL), Ubuntu (and other Debian-based OS), Fedora (and other RedHat-based OS), and MacOS have been updated to mitigate broken dependency issues.

requirements.txt now has versioning.

functionality to build wheel file has been changed to account for new wheel filename rules.

### CODE REVIEW

**Comment by eugenhu** [comment]
Hello, I see from your github bio you're a student at the University of Melbourne. I haven't been maintaining this project for quite some time now. I'm just wondering what your plans are for opendrop. I see you're potentially trying to integrate https://github.com/jdber1/conan-ml into this project?

**Comment by SamSike** [comment]
Hi Eugene,
Yes, I am currently undertaking the Master of Software Engineering Capstone
subject wherein our project is to integrate conan-ml with opendrop.

This here is the first milestone as requested by our client, Daniel Shaw.

This is the version of OpenDrop with minimal changes to the actual code. It
simply fixes the build process so it can now be compiled on any OS. It also
includes the installation guides for the same as they were outdated.

If you remember Tori from one of the issues on GitHub for this project, she
is working in our team as well.

We will not be pushing any more code to this repository until the end of
our subject in June or July 2025. We are only pushing this change so it is
usable/installable in the meantime.

There are however 2 things I would like to request from you.
1. Provide Daniel access to merge pull requests into this git repository,
or merge it yourself when the pull request is created in June or July 2025.
2. Provide details of how you created the windows .msi installable release.
I have been searching online and I see different ways of doing it but I
would prefer if the releases were created the same way as in previous
versions of OpenDrop.

As for more details about our project, we are open to any questions so
please don't hesitate to ask us. The main design choices we have made
however, include:

1. Use customtkinter to create modern looking UI, that has an easier
learning curve for us and any future software devs that work on this
project. GTk3 is old and hard to learn in our opinion.

2. Use conan-ml as the base and integrate opendrop functionality into it.
This was chosen since python is part of our core strengths but we found it
reslly hard to understand the opendrop code as it is too modular. Adding
functionality was also a pain. Since conan-ml is one folder of all the
functionality, we can create our own modularity from scratch, while
providing documentation to the next maintainers as well.

That is the gist of the design choices we have made. These will not be
pushed to OpenDrop until 2025 June or July. The current pull request only
includes an installable version of OpenDrop with installation guides.
Kindly approve that PR for the same.


Regards

Sameer Sikka

Requirements Lead for OpenDrop2

**Comment by eugenhu** [comment]
Hi Sameer,

Can I email you on the email address you have on your github profile? I'm happy to provide any assistance you need in salvaging any usable code from this repo to conan-ml. I no longer have time to maintain this repo and I have been hoping someone else could take over responsibility for this project.

The main functionality I believe should be easy to extract from here is the axis-symmetric Young-Laplace curve fitting, and maybe the code to work with GenICam cameras.

We can discuss this further in a video call, say 2/3 November? I can also say more about how I packaged this python library as a standalone windows application. We can organise a date and time over email.

**Comment by SamSike** [comment]
Hi Eugene,

Sure, I can attend either Nov 2 or Nov 3. My project lead and other
teammates might also like to join in for the meeting if you don't mind.

My contact email is ***@***.***, since this is a uni
related project. I would like to remain a Contributor for this project
after the subject ends, however (and I imagine my teammates would do the
same), so we can take up that responsibility.

Please let me know what time you would prefer for the meeting to be, and we
can set up a zoom meeting. I'll send you an invite for the same. If
possible, please use AEDT.

Regards
Sameer Sikka

**Comment by eugenhu** [comment]
By the way, your email got redacted in github. I've sent you an email to the address you have on your github profile, were you able to receive it?

**Pull request merged**
